### ISSUE TITLE
Content-Type header overwritten

### ISSUE THREAD

**Issue by colehudson** [WSULib/ouroboros#39]
It looks like the Content-Type header is overwritten when an outside request through the reverse proxy. Not sure if it's the fault of Apache or Twisted. Maybe a better place for this issue would be in /fedora-stack. Will investigate.

**Comment by ghukill** [comment]
Nice find.  This seems appropriate as any, with changes potentially in other areas.

**Comment by colehudson** [comment]
Closed. See https://github.com/WSULib/digitalcollections/issues/21.
