### ISSUE TITLE
caching

### ISSUE THREAD

**Issue by ghukill** [WSULib/ouroboros#42]
This is a big one.  Look into:

  * placement of Varnish
    * before and after Loris only?  
  * remove things from cache

**Comment by colehudson** [comment]
Adding what we've done here to address caching. Varnish currently sits out in front of Apache. It has a few exceptions for internal applications that don't need caching and other security measures. Methods are now built into Ouroboros that handle re-indexing to Varnish. Still more work to do to better control and understand when items are cached and iron out its interaction with Loris. WIll leave this issue open for now.

**Comment by ghukill** [comment]
Looking pretty stable - can open issues for specifics if they crop up, but there is a nice non-cached version at `http` for those with green-lit IPs
